### ISSUE TITLE
publish for Scala 2.13.0-M5, please?

### ISSUE THREAD

**Issue by SethTisue** [typelevel/jawn#120]
this is blocking circe at https://github.com/circe/circe/pull/1015

**Comment by SethTisue** [comment]
does anyone else publishing rights in this repo, or only @non?

**Comment by SethTisue** [comment]
I see there's already a PR at https://github.com/non/jawn/pull/117

**Comment by eed3si9n** [comment]
https://github.com/typelevel/jawn/pull/117 is merged now.

**Comment by travisbrown** [comment]
What do people think about publishing an 0.14.0 after #137 lands?

**Comment by eed3si9n** [comment]
@travisbrown Sounds good to me.

**Comment by non** [comment]
👍

**Comment by non** [comment]
Just merged #137 which I think handles all the major issues we know about, so it seems like a good time for a release.

If one of the new maintainers wants to try that could be good. Otherwise I'll take a crack at it after work tonight.

**Comment by travisbrown** [comment]
Thanks, @non! I can take the release—I'll be able to get to it in an hour or two.

**Comment by non** [comment]
@travisbrown Go for it!

**Comment by travisbrown** [comment]
It's done! https://github.com/typelevel/jawn/releases/tag/v0.14.0

**Comment by SethTisue** [comment]
* https://repo1.maven.org/maven2/org/typelevel/jawn-parser_2.13.0-M5/0.14.0/
* scala/make-release-notes@019020f2d7948598b8fbfe820a533291ecb7d2b6
