### ISSUE TITLE
Move to Typelevel?

### ISSUE THREAD

**Issue by travisbrown** [typelevel/jawn#126]
The lack of a 2.13.0-M5 release for jawn-parser has been blocking a circe release for 2.13.0-M5 for over a month now, and @eed3si9n has [a working PR](https://github.com/non/jawn/pull/117) open that's two months old with no feedback from any Jawn maintainers (which as far as I know is just Erik?).

I asked [on Gitter last month](https://gitter.im/non/jawn?at=5be956766b9822140d19f974) about things us non-maintainers could do to help speed up PR merges and releases, also with no response.

@non (and @milessabin, @ceedubs, @larsrh, etc.), how would you feel about moving the project to https://github.com/typelevel/jawn and publishing to `org.typelevel`? This would spread the maintenance burden and let us avoid blocking everything downstream for weeks or months at a time. If you'd like, @non, we could agree on some kind of arrangement that would require your approval for any non-trivial changes.

/cc @SethTisue

**Comment by non** [comment]
Hey this is a good plan. I'm in favor 👍

**Comment by non** [comment]
I'm traveling for work but I'll try to message other people privately about sharing maintainership.

**Comment by eed3si9n** [comment]
You know you created something cool when this conversation happens :) Congrats Erik and thanks for Jawn.

**Comment by dwijnand** [comment]
If you change the groupId, could you make sure to change the package name too, please?

**Comment by larsrh** [comment]
With @non being in favour, I think we can open the corresponding issue for Typelevel membership in typelevel/general. As far as I can tell, all requirements are satisfied.

**Comment by larsrh** [comment]
Membership approved. We can go forward with this.

@non, I'd appreciate if you could transfer this repository to the Typelevel organization.

**Comment by non** [comment]
Just moved the repo to `typelevel/jawn`. I'm in the process of updating the README, etc.

**Comment by non** [comment]
Alright at this point I've merged https://github.com/typelevel/jawn/pull/128 and moved the repo. I've message some folks privately about being additional maintainers. Once I hear back from at least a few of them I'll update the repo permissions, at which point I will stop being a single-point of failure (I hope).

**Comment by non** [comment]
(Also, apologies for the delay. My flight back from SF was severely delayed and I got stranded in Charlotte, and only got back yesterday.)

**Comment by non** [comment]
Alright, I've added 3 new maintainers (thanks to @rossabaker, @travisbrown, and @dwijnand) and updated the README. This will be the last time I push directly to `master`.

I'm going to go ahead and close this issue now. Thanks again @travisbrown for suggesting this long-overdue step.
