### ISSUE TITLE
publish for Scala 2.13.0-RC1

### ISSUE THREAD

**Issue by xuwei-k** [typelevel/jawn#160]

**Comment by SethTisue** [comment]
blocked by claimant, which is blocked by cats

**Comment by travisbrown** [comment]
@d6 Would you be willing to remove `CatsClaimTest` in Claimant? I'd like to use Claimant in e.g. circe, but having yet another Cats dependency to wait on doesn't seem ideal, especially since there's a lot of overlap with `ClaimTest` here and I'm not sure the Cats dep adds anything.

**Comment by travisbrown** [comment]
Done: https://github.com/typelevel/jawn/releases/tag/v0.14.2
