### ISSUE TITLE
Pruning of support modules

### ISSUE THREAD

**Issue by rossabaker** [typelevel/jawn#162]
To simplify our build, I propose that we drop two integrations:

* argonaut: maintained as an argonaut module, so ours is redundant

* rojoma: as yet unpublished for Scala 2.13, making the build more complex.  I'm not aware that it's widely used enough to merit the workarounds.  Not hard to revive if it publishes for 2.13 and people complain.

**Comment by non** [comment]
Agreed on both counts.
