### ISSUE TITLE
Support source locations

### ISSUE THREAD

**Issue by djrenren** [typelevel/jawn#267]
It would be really helpful if there was a way to extract source locations (for example byte offset and length) through either the AST or even just the Facade interface. That way any downstream validation of the JSON can report accurate error locations.

**Comment by rossabaker** [comment]
There may be tension here between enabling that and being as fast as possible, but it's a nice idea if the implementation performs.

**Comment by djrenren** [comment]
Hmm so actually, looking over the definitions for Facade, there's already support for locations (well, indices but close enough) at the start of the token. I imagine that supplying the index at the end wouldn't really hurt performance since it's sitting around anyway.

**Comment by rossabaker** [comment]
Breaking changes are painful, now that a few JSON libraries are using jawn as their internal parser.  But I'd be interested in an API proposal that preserved compatibility for this.

**Comment by travisbrown** [comment]
As a side note, I've been intending to add support for character offsets in failure to Circe for years, but it hasn't been a priority for me because in general I've found path-style locations (which have always been supported) more useful. I'd be happy to review an implementation, or to work on it myself if someone wanted to pay for it.

**Comment by djrenren** [comment]
@rossabaker I've managed to build my own parser that extracts source spans by extending CharBasedParser and implementing a Facade that recorded indices. It was actually not too difficult so major props on the design of this library! :D 

The only thing I wasn't able to do was get precise string lengths due to string escaping shenanigans. In `jnum` we can trust the `CharSequence` length to be the same as the representation's length, but in`jstring` the `CharSequence` has already resolved any escaped characters which means its length is not equal to the representation's length.

This appears to be the only blocker from a core design standpoint. The rest would be AST representations decisions. which I'm a bit more ambivalent on. Could we get away with just adding an overload for `jstring` that contains a `length: Int` or `end_index: Int` parameter, and have a default implementation to call the `jstring` that exists today?

**Comment by rossabaker** [comment]
I would expect that to be compatible now that 2.11 support is dropped.  We'll see what MiMa says, but that approach sounds reasonable to me.
