### ISSUE TITLE
JValue.asInt/getInt methods

### ISSUE THREAD

**Issue by ijuma** [typelevel/jawn#34]
It would be handy to have convenience methods for retrieving a number as an Int (quite a common need). This is easily done as an extension method, so I understand if you don't think it should be part of the AST, but I thought I'd bring it up for discussion.

**Comment by non** [comment]
I'll probably go ahead and add it. Thanks for the comment.

**Comment by tapmania** [comment]
On a related note, should we also have an IntNum case class?

**Comment by non** [comment]
@tapmania I think using `LongNum` and truncating it is fine. I'd rather not have more subclasses than necessary.

**Comment by tapmania** [comment]
I have a PR out for this. Please have a look: https://github.com/non/jawn/pull/63
