### ISSUE TITLE
Add Scala.js support

### ISSUE THREAD

**Issue by ghost** [typelevel/jawn#38]
For extra points, please refer to Reference https://gitter.im/non/jawn?at=55a7ae4de881cbd76356e350 Summary: 

> InTheNow: Main issues are `ReadableByteChannel` and j`ava.io - File, FileInputStream`
> sjrd: No, java.io.File cannot be implemented in Scala.js. 
> sjrd:     You could implement in Scala.js-goodies-for-Node.js, but not in general, obviously. 
> non: we could potentially try to make the I/O parts JVM only
> sjrd: Yes, that would probably be the best thing to do, here.

**Comment by armanbilge** [comment]
Implemented in #351.
