### ISSUE TITLE
Release v1.4.0 please :)

### ISSUE THREAD

**Issue by armanbilge** [typelevel/jawn#466]
Sorry, just trying to propagate that Native/Scala 3 artifact 😅

**Comment by armanbilge** [comment]
Actually the Scala 3.1.3 upgrade fixes an annoying Scala.js issue as well.

**Comment by rossabaker** [comment]
#438 is in flight and still broken, but we won't run out of numbers...

**Comment by rossabaker** [comment]
Releasing.

**Comment by armanbilge** [comment]
Oh, I missed the new activity there. I love a good bincompat puzzler, let me poke my nose in.
