### ISSUE TITLE
Make new release for Jawn

### ISSUE THREAD

**Issue by mdedetrich** [typelevel/jawn#527]
As mentioned in discord, a new feature was merged into Jawn (see https://github.com/typelevel/jawn/pull/438) and Jawn hasn't been release with this new feature for some time (last release of Jawn is 1.4.0 which is Jul 2022, almost a year ago).

Since Scala 3.3 LTS is likely to come out very soon maybe it makes sense to release Jawn when updated with Scala 3.3 so we don't do unnecessary extra releases?

@eed3si9n @rossabaker @dwijnand

**Comment by mdedetrich** [comment]
PR for Scala 3.3 is ready https://github.com/typelevel/jawn/pull/535

**Comment by rossabaker** [comment]
Released as v1.5.0.
