### ISSUE TITLE
Support for play 2.6 using scala 2.11

### ISSUE THREAD

**Issue by bmontuelle** [typelevel/jawn#94]
#90 Added support for play 2.6
Unfortunately, my project still has a lot of dependencies available for scala 2.11, thus I'm sticking with the 2.11 version of Play

If I add depdendency to `"org.spire-math"           %% "jawn-play"                 % "0.11.0"` 
the play-json 2.5.15 dep gets evicted (its defined to 2.6.1 in my dependencies)

If I use `"org.spire-math"           % "jawn-play_2.12"                 % "0.11.0"`  I get a cross version conflict on jawn-play and its dependencies

Do you think theres a possible solution to build a play 2.6 support with scala 2.11 ? I've copied the Parser.scala locally to depende only on `jawn-parser`in the meantime

Thanks a lot

**Comment by xuwei-k** [comment]
https://repo1.maven.org/maven2/org/typelevel/jawn-play_2.11/0.14.0/jawn-play_2.11-0.14.0.pom
